# Generated by Django 4.1.2 on 2023-02-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_first', models.CharField(max_length=999999999)),
                ('header_sec', models.CharField(max_length=999999999)),
                ('header_thrd', models.CharField(max_length=999999999)),
                ('header_fourth', models.CharField(max_length=999999999)),
            ],
        ),
    ]
