# Generated by Django 4.1.2 on 2023-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angularproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderText', models.CharField(max_length=1500)),
            ],
        ),
        migrations.RenameField(
            model_name='innertext',
            old_name='header_first',
            new_name='ProjectText',
        ),
        migrations.RemoveField(
            model_name='innertext',
            name='header_fourth',
        ),
        migrations.RemoveField(
            model_name='innertext',
            name='header_sec',
        ),
        migrations.RemoveField(
            model_name='innertext',
            name='header_thrd',
        ),
    ]
