# Generated by Django 4.1.2 on 2023-03-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InnerText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectText', models.CharField(max_length=999999999)),
            ],
        ),
        migrations.CreateModel(
            name='TitleText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HeaderText', models.CharField(max_length=1500)),
            ],
        ),
    ]
