# Generated by Django 4.1.2 on 2023-01-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='welcometext',
            name='welcome_header',
        ),
    ]
